### ISSUE TITLE
Problem in startup

### ISSUE THREAD

**Issue by erichmccartney** [erichmccartney/DataGov_API#1]
I edited line 28 to include the option attributes in an attempt to resolve an error in the below method starting on line 46.

I think this is something do to do with the class example using dotnet 2.1 verse the 5.0 I used.... but idk.

https://github.com/erichmccartney/DataGov_API/blob/5d8350651eab7c2259053814d713ec26e7e6b060/DataGov_API/Startup.cs#L28

https://github.com/erichmccartney/DataGov_API/blob/5d8350651eab7c2259053814d713ec26e7e6b060/DataGov_API/Startup.cs#L46-L51

**Comment by mattgwagner** [comment]
https://stackoverflow.com/questions/58455770/replacing-usemvc-in-net-core-3-0 ?

![image](https://user-images.githubusercontent.com/157644/120036202-c341c380-bfcd-11eb-938e-17dca276a4d4.png)

**Comment by erichmccartney** [comment]
it works!

https://github.com/erichmccartney/DataGov_API/blob/b8ed63144143f3e7e106baa4c58a4f5a65dfbd0f/DataGov_API/Startup.cs#L28

https://github.com/erichmccartney/DataGov_API/blob/b8ed63144143f3e7e106baa4c58a4f5a65dfbd0f/DataGov_API/Startup.cs#L44-L51
